### ISSUE TITLE
Incorrect state of contains method of BinaryPrefs after creation

### ISSUE THREAD

**Issue by SavinMike** [iamironz/binaryprefs#31]
When I create new instance of binary prefs `contains(String)` method work incorrect:

```
final SharedPreferences sharedPreferences = prefsProvider.providePrefs(prefsName);
if (sharedPreferences == null) {
	return;
}

Log.d("PrefsTest", "binaryPrefs contains " + key +":" + sharedPreferences.contains(key));
if (!sharedPreferences.contains(key)) {
	Log.d("PrefsTest", "print all prefs: " + sharedPreferences.getAll());
	Log.d("PrefsTest", "binaryPrefs contains " + key +":" + sharedPreferences.contains(key));
	if (!sharedPreferences.contains(key)) {
		return;
	}
}
```
PrefsProvider create new instance of binary prefs. 

After calling this code you can see next logs:
```
binaryPrefs contains application_id:false
PrefsTest: print all prefs: {application_id=XXXXX}
binaryPrefs contains application_id:true
```
When I was calling `sharedPreferences.getAll()` method, `sharedPreferences.contains` start work correct

**Comment by iamironz** [comment]
Hello Mike!

Please can tell me what version of binaryprefs is?
And also one question: this problem replays permanently or not?

Regards,
Alexander

**Comment by SavinMike** [comment]
Version is 1.0.0-BETA-2
This problem is repeated every time when I try to check is this key exist right after creation of prefs

**Comment by iamironz** [comment]
Can you please check and reproduce this problem with last master branch build on clear project>

**Comment by SavinMike** [comment]
Unfortunately, i do not have access to that project. So that i can't check it
